### ISSUE TITLE
Docker image can not build（can release docker image ??? Tired to build）. 

### ISSUE THREAD

**Issue by Whojohn** [dev-moonduck/docker-hadoop#9]
#9 Can not build.

- problem
 Code pull from master can not build which reason  are as follow:
1. debian 10.x not suport apt-get jdk 8 anymore.
2. Make file is wrong path in spark build path .
3. Build successful after fix preview problem .However,  i just can use hive with  beeline inside docker  , can not use 127.0.0.1/localhost connect into hiveservice.
```
# work perfect inside docker
 bin/beeline -u jdbc:hive2://127.0.0.1:10000 -n hive
# fail with jdbc connect outside , such as those url （/tmp/hive/hive.log can not get any fail message）
 jdbc:hive2://127.0.0.1:10000
 jdbc:hive2://localhost:10000

# network outside docker show port is ok!!!
 netstat -na |grep 10000
  TCP    0.0.0.0:10000          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:10000        0.0.0.0:0              LISTENING
  TCP    [::]:10000             [::]:0                 LISTENING
  TCP    [::1]:10000            [::]:0                 LISTENING


```

- Suggest
1. release docker image for per-build version?
2. maybe using per-build docker image as env is better choice.(such as adoptopenjdk/openjdk8:jdk8u-debianslim-nightly)

**Comment by dev-moonduck** [comment]
@Whojohn Sorry for very very late reply back, Also I'm regret to say this image is not stable yet.
I am trying my best to dedicate this project whenever I have time.
I will fix and tag release version when it is stable.
And thanks for your suggestion, will check.
